<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/time-packages.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?= $this->translate("ELENCO PACCHETTI MINUTI DISPONIBILI"); ?></h3>
            </div>
            <div class="col-lg-6">
                <a href="<?php echo $this->url('time-packages/buy'); ?>" class="btn btn-success pull-right"><i class="fa fa-shopping-cart"></i> <?= $this->translate("Acquista pacchetto"); ?></a>
            </div>
        </div>

        <hr>
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?= $this->translate("Elenco Pacchetti minuti"); ?>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="js-time-packages-table">
                    <thead>
                    <tr>
                        <th><?= $this->translate("Nome e cognome"); ?></th>
                        <th><?= $this->translate("Email"); ?></th>
                        <th><?= $this->translate("Stato"); ?></th>
                        <th><?= $this->translate("Selezione"); ?></th>
                    </tr>
                    </thead>

                </table>
            </div>
        </div>
    </div>
</div>