<?php
$this->headLink()->appendStylesheet($this->basePath() .'/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile($this->basePath() .'/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile($this->basePath() .'/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/group-add-employees.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?= $this->translate("ELENCO UTENTI DISPONIBILI"); ?></h3>
            </div>
            <div class="col-lg-6">
                <a href="<?php echo $this->url('groups/details', ['id' => $this->group->getId()]); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna al gruppo"); ?></a>
            </div>
        </div>

        <form method="post">
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn green pull-right"><i class="fa fa-plus"></i> <?= $this->translate("Aggiungi Dipendenti selezionati"); ?></button>
                </div>
            </div>
            <hr>
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cogs"></i><?= $this->translate("Elenco Utenti"); ?>
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="js-group-add-employees-table">
                        <thead>
                        <tr>
                            <th class="button-column"><?= $this->translate("Seleziona"); ?></th>
                            <th class="name-column"><?= $this->translate("Nome e cognome"); ?></th>
                            <th class="email-column"><?= $this->translate("Email"); ?></th>
                            <th class="status-column"><?= $this->translate("Stato"); ?></th>
                        </tr>
                        </thead>
                        <?php /** @var \BusinessCore\Entity\BusinessEmployee $be */
                        foreach ($this->group->getBusiness()->getEnabledBusinessEmployeesWithoutGroup() as $be):
                            $employee = $be->getEmployee(); ?>
                            <tr>
                                <td>
                                    <label><input type="checkbox" name="add-<?= $employee->getId() ?>"></label>
                                </td>
                                <td><?= $employee->getName() . " " . $employee->getSurname(); ?></td>
                                <td><?= $employee->getEmail(); ?></td>
                                <td><?= $this->businessEmployeeStatus($be->getStatus()); ?></td>

                            </tr>
                            <?php
                        endforeach; ?>
                    </table>
                </div>
            </div>
        </form>
    </div>
</div>