<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/group-details.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?= $this->translate("DETTAGLI GRUPPO ") . strtoupper('"' .$this->group->getName() . '"'); ?></h3>
            </div>
            <div class="col-lg-6">
                <a href="<?php echo $this->url('groups'); ?>" class="btn btn-success pull-right"><i class="fa fa-arrow-left"></i> <?= $this->translate("Torna alla lista"); ?></a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <a href="<?= $this->url('groups/details/add-employees', ['id' => $this->group->getId()]); ?>" class="btn green pull-right"><i class="fa fa-plus"></i> <?= $this->translate("Aggiungi Dipendenti"); ?></a>
            </div>
        </div>
        <hr>
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?= $this->translate("Elenco Dipendenti"); ?>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="js-employees-group-table">
                    <thead>
                    <tr>
                        <th class="name-column"><?= $this->translate("Nome e cognome"); ?></th>
                        <th class="email-column"><?= $this->translate("Email"); ?></th>
                        <th class="status-column"><?= $this->translate("Stato"); ?></th>
                        <th class="button-column"><?= $this->translate("Azioni"); ?></th>
                    </tr>
                    </thead>
                    <?php /** @var \BusinessCore\Entity\BusinessEmployee $be */
                    foreach ($this->group->getBusinessEmployee() as $be):
                        $employee = $be->getEmployee(); ?>
                        <tr>
                            <td><?= $employee->getName() . " " . $employee->getSurname(); ?></td>
                            <td><?= $employee->getEmail(); ?></td>
                            <td><?= $this->businessEmployeeStatus($be->getStatus()); ?></td>
                            <td>
                                <a href="<?= $this->url('groups/details/remove-employee', ['id' => $this->group->getId(), 'employee' => $employee->getId()]); ?>"
                                   onclick="return confirm('<?= $this->translate("Sei sicuro di voler eliminare questo utente?"); ?>')"
                                   class="validation-btn btn btn-warning btn-xs">
                                    <?= $this->translate("Rimuovi dal gruppo"); ?>
                                </a>
                            </td>
                        </tr>
                        <?php
                    endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>