<?php
$this->headLink()->appendStylesheet($this->basePath() .'/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile($this->basePath() .'/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile($this->basePath() .'/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/groups.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-title"><?= $this->translate("ELENCO GRUPPI"); ?></h3>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <a href="<?= $this->url('groups/add'); ?>" class="btn green pull-right"><i class="fa fa-plus"></i> <?= $this->translate("Crea nuovo Gruppo"); ?></a>
            </div>
        </div>
        <hr>
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?= $this->translate("Elenco Gruppi"); ?>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="js-groups-table">
                    <thead>
                    <tr>
                        <th><?= $this->translate("ID"); ?></th>
                        <th><?= $this->translate("Nome"); ?></th>
                        <th><?= $this->translate("Descrizione"); ?></th>
                        <th><?= $this->translate("N° dipendenti"); ?></th>
                        <th><?= $this->translate("Azioni"); ?></th>
                    </tr>
                    </thead>
                    <?php /** @var \BusinessCore\Entity\Group $group */
                    foreach ($this->business->getBusinessGroups() as $group): ?>
                        <tr>
                            <td><?= $group->getId() ?></td>
                            <td><?= $group->getName(); ?></td>
                            <td><?= $group->getDescription(); ?></td>
                            <td><?= count($group->getBusinessEmployees()) ?></td>
                            <td>
                                <a href="<?= $this->url('groups/details', ['id' => $group->getId()]); ?>"
                                   class="validation-btn btn btn-default btn-xs">
                                    <?= $this->translate("Dettagli"); ?>
                                </a>
                            </td>
                        </tr>
                        <?php
                    endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>