<?php
use BusinessCore\Entity\Base\BusinessPayment;

$this->headLink()
    ->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
    ->appendStylesheet('/js/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile($this->basePath() .'/js/business-payments.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- Header -->
        <h3 class="page-title">
            <?= $this->translate("ELENCO PAGAMENTI"); ?>
        </h3>

        <div class="page-bar">
        </div>

        <!-- Content -->
        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-5">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="type"><?= $this->translate("Tipologia"); ?></option>
                                    <option value="status"><?= $this->translate("Stato pagamento"); ?></option>
                                </select>
                            </div>
                            <div class="form-group">
                                <select name="js-payment-type" id="js-payment-type" class="form-control" style="display: none;">
                                    <option value="<?= BusinessPayment::TYPE_PACKAGE ?>"><?= $this->translate("Pacchetto minuti"); ?></option>
                                    <option value="<?= BusinessPayment::TYPE_TRIP ?>"><?= $this->translate("Corsa"); ?></option>
                                    <option value="<?= BusinessPayment::TYPE_EXTRA ?>"><?= $this->translate("Extra/penale"); ?></option>
                                    <option value="<?= BusinessPayment::TYPE_SUBSCRIPTION ?>"><?= $this->translate("Sottoscrizione"); ?></option>
                                </select>
                                <select name="js-payment-status" id="js-payment-status" class="form-control" style="display: none;">
                                    <option value="<?= BusinessPayment::STATUS_PENDING ?>"><?= $this->translate("Non pagato"); ?></option>
                                    <option value="<?= BusinessPayment::STATUS_EXPECTED_PAYED ?>"><?= $this->translate("Pagato ma in attesa di conferma"); ?></option>
                                    <option value="<?= BusinessPayment::STATUS_CONFIRMED_PAYED ?>"><?= $this->translate("Pagato"); ?></option>
                                    <option value="<?= BusinessPayment::STATUS_INVOICED ?>"><?= $this->translate("Fatturato"); ?></option>
                                    <option value="<?= BusinessPayment::STATUS_CANCELLED ?>"><?= $this->translate("Cancellato"); ?></option>
                                </select>
                                <input type="text" name="value" value="" class="form-control" id="js-value"
                                       placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="form-inline">
                            <div class="form-group">
                                <label> <?= $this->translate("Data inserimento da"); ?>: </label>
                                <input class="form-control form-control-inline input-small date-picker" size="16"
                                       type="text" id="js-date-from"
                                       placeholder="<?= $this->translate("Data inizio"); ?>">
                            </div>
                            <div class="form-group">
                                <label> <?= $this->translate("a"); ?>: </label>
                                <input class="form-control form-control-inline input-small date-picker" size="16"
                                       type="text" id="js-date-to"
                                       placeholder="<?= $this->translate("Data fine"); ?>">
                            </div>

                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search"><i
                                        class="fa fa-search"></i> <?= $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i
                                        class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a id="js-clear">
                                            <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- filter container -->

                <hr>

                <!-- Datatable container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-money"></i><?= $this->translate("Elenco Pagamenti"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table class="table table-striped table-bordered table-hover" id="js-business-payments-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("Data inserimento"); ?></th>
                                <th><?= $this->translate("Tipologia"); ?></th>
                                <th><?= $this->translate("Importo"); ?></th>
                                <th><?= $this->translate("Stato pagamento"); ?></th>
                                <th><?= $this->translate("Data pagamento"); ?></th>
                                <th><?= $this->translate("Dettagli"); ?></th>
                            </tr>
                            </thead>
                        </table>
                        <table class="table table-striped table-bordered table-hover" id="report-table" style="display: none;">
                            <tr>
                                <td style="font-size: 14px;vertical-align:middle"><?= $this->translate("Importo totale dati filtrati"); ?> </td>
                                <td style="font-size: 14px;vertical-align:middle"><div id="report-total"></div></td>
                                <td style="font-size: 14px;"><div class="btn btn-link" id="report-download"><?= $this->translate("download report"); ?></div></td>
                            </tr>
                        </table>
                        <!-- table -->
                    </div>
                </div>
                <!-- datatable container -->
            </div>
        </div>
        <!-- content -->
    </div>
</div>