<?php
$this->headLink()->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile($this->basePath() .'/js/business-payments.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- Header -->
        <h3 class="page-title">
            <?= $this->translate("ELENCO PAGAMENTI"); ?>
        </h3>

        <div class="page-bar">
        </div>

        <!-- Content -->
        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="bp.type"><?= $this->translate("Tipologia"); ?></option>

                                </select>
                            </div>
                            <div class="form-group">
                                <select name="js-payment-type" id="js-payment-type" class="form-control" style="display: none;">
                                    <option value="time_package"><?= $this->translate("Pacchetto minuti"); ?></option>
                                    <option value="trip"><?= $this->translate("Corsa"); ?></option>
                                </select>
                                <select name="js-payment-status" id="js-payment-status" class="form-control" style="display: none;">
                                    <option value="1"><?= $this->translate("Pagato"); ?></option>
                                    <option value=null><?= $this->translate("Non pagato"); ?></option>
                                </select>
                                <input type="text" name="value" value="" class="form-control" id="js-value"
                                       placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search"><i
                                        class="fa fa-search"></i> <?= $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i
                                        class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a id="js-clear">
                                            <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- filter container -->

                <hr>

                <!-- Datatable container -->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?= $this->translate("Elenco Pagamenti"); ?>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <!-- Table -->
                        <table class="table table-striped table-bordered table-hover" id="js-business-payments-table">
                            <thead>
                            <tr>
                                <th><?= $this->translate("Data inserimento"); ?></th>
                                <th><?= $this->translate("Tipologia"); ?></th>
                                <th><?= $this->translate("Importo"); ?></th>
                                <th><?= $this->translate("Stato pagamento"); ?></th>
                            </tr>
                            </thead>
                        </table>
                        <!-- table -->
                    </div>
                </div>
                <!-- datatable container -->
            </div>
        </div>
        <!-- content -->
    </div>
</div>