
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-users"></i><?= $this->title ?>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover" id="<?= $this->tableId ?>">
            <thead>
            <tr>
                <th class="name-column"><?= $this->translate("Nome e cognome"); ?></th>
                <th class="email-column"><?= $this->translate("Email"); ?></th>
                <th class="group-column"><?= $this->translate("Gruppo"); ?></th>
                <th class="status-column"><?= $this->translate("Stato"); ?></th>
                <th class="status-column"><?= $this->translate("Inserimento"); ?></th>
                <th class="status-column"><?= $this->translate("Confermato"); ?></th>
                <th class="pin-column"><?= $this->translate("PIN Aziendale"); ?></th>
                <th class="button-column"><?= $this->translate("Azioni"); ?></th>
            </tr>
            </thead>
            <?php /** @var \BusinessCore\Entity\BusinessEmployee $be */
            foreach ($this->list as $be):
                $employee = $be->getEmployee();
                $companyPinStatus = $employee->isBusinessPinDisabled() ? $this->translate("(disabilitato)") : '';
                ?>
                <tr>
                    <td><?= $employee->getName() . " " . $employee->getSurname(); ?></td>
                    <td><?= $employee->getEmail(); ?></td>
                    <td><?= $this->groupLink($be) ?></td>
                    <td><?= $this->businessEmployeeStatus($be->getStatus()); ?></td>
                    <td><?= $be->getReadableInsertDate() ?></td>
                    <td><?= $be->getReadableConfirmedDate() ?></td>
                    <td><?= $employee->getBusinessPin()?> <?= $companyPinStatus ?></td>
                    <td><?= $this->businessEmployeeAvailableActionButtons($be) ?></td>
                </tr>
                <?php
            endforeach; ?>
        </table>
    </div>
</div>