<?php
/** @var EmployeeLimits $limits */
use BusinessCore\Helper\EmployeeLimits;

$limits = $this->limits;
?>

<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-users"></i><?= $this->translate("Orari e giorni consentiti"); ?>
        </div>
    </div>

        <div class="portlet-body">
            <form method="post">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th ><?= $this->translate("Giorno"); ?></th>
                        <th ><?= $this->translate("Corsa abilitata"); ?></th>
                        <th ><?= $this->translate("Regole"); ?></th>
                    </tr>
                </thead>
                <tr>
                    <td><?= $this->translate("Lunedì"); ?></td>
                    <td><input type="checkbox" <?= $limits->isMondayEnabled() ? 'checked' : '' ?> name="mo-cb"></td>
                    <td>
                        <input id="mo" type="hidden" name="mo">
                        <div class="input-field-wrap">
                            <button data-day="mo" class="btn btn-small add-field-btn"><?= $this->translate("Aggiungi regola"); ?></button>

                            <?php
                            foreach ($limits->getMondayRanges() as $range) {
                                echo $this->partial('partials/time-limit-row.phtml', [
                                    'class' => 'mo-rules',
                                    'from' => $range['from'],
                                    'to' => $range['to'],
                                ]);
                            }
                            ?>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><?= $this->translate("Martedì"); ?></td>
                    <td><input type="checkbox" <?= $limits->isTuesdayEnabled() ? 'checked' : '' ?> name="tu-cb"></td>
                    <td>
                        <input id="tu" type="hidden" name="tu">
                        <div class="input-field-wrap">
                            <button data-day="tu" class="btn btn-small add-field-btn"><?= $this->translate("Aggiungi regola"); ?></button>

                            <?php
                            foreach ($limits->getTuesdayRanges() as $range) {
                                echo $this->partial('partials/time-limit-row.phtml', [
                                    'class' => 'tu-rules',
                                    'from' => $range['from'],
                                    'to' => $range['to'],
                                ]);
                            }
                            ?>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><?= $this->translate("Mercoledì"); ?></td>
                    <td><input type="checkbox"  <?= $limits->isWednesdayEnabled() ? 'checked' : '' ?> name="we-cb"></td>
                    <td>
                        <input id="we" type="hidden" name="we">
                        <div class="input-field-wrap">
                            <button data-day="we" class="btn btn-small add-field-btn"><?= $this->translate("Aggiungi regola"); ?></button>

                            <?php
                            foreach ($limits->getWednesdayRanges() as $range) {
                                echo $this->partial('partials/time-limit-row.phtml', [
                                    'class' => 'we-rules',
                                    'from' => $range['from'],
                                    'to' => $range['to'],
                                ]);
                            }
                            ?>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><?= $this->translate("Giovedì"); ?></td>
                    <td><input type="checkbox" <?= $limits->isThursdayEnabled() ? 'checked' : '' ?> name="th-cb"></td>
                    <td>
                        <input id="th" type="hidden" name="th">
                        <div class="input-field-wrap">
                            <button data-day="th" class="btn btn-small add-field-btn"><?= $this->translate("Aggiungi regola"); ?></button>

                            <?php
                            foreach ($limits->getThursdayRanges() as $range) {
                                echo $this->partial('partials/time-limit-row.phtml', [
                                    'class' => 'th-rules',
                                    'from' => $range['from'],
                                    'to' => $range['to'],
                                ]);
                            }
                            ?>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><?= $this->translate("Venerdì"); ?></td>
                    <td><input type="checkbox" <?= $limits->isFridayEnabled() ? 'checked' : '' ?> name="fr-cb"></td>
                    <td>
                        <input id="fr" type="hidden" name="fr">
                        <div class="input-field-wrap">
                            <button data-day="fr" class="btn btn-small add-field-btn"><?= $this->translate("Aggiungi regola"); ?></button>

                            <?php
                            foreach ($limits->getFridayRanges() as $range) {
                                echo $this->partial('partials/time-limit-row.phtml', [
                                    'class' => 'fr-rules',
                                    'from' => $range['from'],
                                    'to' => $range['to'],
                                ]);
                            }
                            ?>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><?= $this->translate("Sabato"); ?></td>
                    <td><input type="checkbox" <?= $limits->isSaturdayEnabled() ? 'checked' : '' ?> name="sa-cb"></td>
                    <td>
                        <input id="sa" type="hidden" name="sa">
                        <div class="input-field-wrap">
                            <button data-day="sa" class="btn btn-small add-field-btn"><?= $this->translate("Aggiungi regola"); ?></button>

                            <?php
                            foreach ($limits->getSaturdayRanges() as $range) {
                                echo $this->partial('partials/time-limit-row.phtml', [
                                    'class' => 'sa-rules',
                                    'from' => $range['from'],
                                    'to' => $range['to'],
                                ]);
                            }
                            ?>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><?= $this->translate("Domenica"); ?></td>
                    <td><input type="checkbox" <?= $limits->isSundayEnabled() ? 'checked' : '' ?> name="su-cb"></td>
                    <td>
                        <input id="su" type="hidden" name="su">
                        <div class="input-field-wrap">
                            <button data-day="su" class="btn btn-small add-field-btn"><?= $this->translate("Aggiungi regola"); ?></button>

                            <?php
                            foreach ($limits->getSundayRanges() as $range) {
                                echo $this->partial('partials/time-limit-row.phtml', [
                                    'class' => 'su-rules',
                                    'from' => $range['from'],
                                    'to' => $range['to'],
                                ]);
                            }
                            ?>
                        </div>
                    </td>
                </tr>

            </table>
            <input id="save-limits" type="submit" value="Salva">
            </form>
        </div>

    <!--template for new fields-->
    <div id="rule-template" class="rule-div hide" style="clear: both;">
        <div class="control-group col-sm-2">
            <div class="input-group clockpicker">
                <input type="text" class="from form-control" placeholder="<?= $this->translate("dalle"); ?>">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
        </div>
        <div class="control-group col-sm-2">
            <div class="input-group clockpicker">
                <input type="text" class="to form-control" placeholder="<?= $this->translate("alle"); ?>">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-time"></span>
                </span>
            </div>
        </div>
        <div class="control-group col-sm-1">
            <div class="remove-times btn btn-icon-only">
                <i class="glyphicon glyphicon-remove"></i>
            </div>
        </div>
    </div>
</div>
