
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-users"></i><?= $this->title ?>
        </div>
    </div>
    <div class="portlet-body">
        <table class="table table-striped table-bordered table-hover" id="<?= $this->tableId ?>">
            <thead>
            <tr>
                <th class="name-column"><?= $this->translate("Nome e cognome"); ?></th>
                <th class="email-column"><?= $this->translate("Email"); ?></th>
                <th class="group-column"><?= $this->translate("Gruppo"); ?></th>
                <th class="status-column"><?= $this->translate("Stato"); ?></th>
                <th class="button-column"><?= $this->translate("Azioni"); ?></th>
            </tr>
            </thead>
            <?php /** @var \BusinessCore\Entity\BusinessEmployee $be */
            foreach ($this->list as $be):
                $employee = $be->getEmployee();
                if (is_null($be->getGroup())) {
                    $groupName = '-';
                } else {
                    $groupName = '<a href="'. $this->url('groups/details', ['id' => $be->getGroup()->getId()]) . '">' . $be->getGroup()->getName() . '</a>';
                } ?>
                <tr>
                    <td><?= $employee->getName() . " " . $employee->getSurname(); ?></td>
                    <td><?= $employee->getEmail(); ?></td>
                    <td><?= $groupName ?></td>
                    <td><?= $this->businessEmployeeStatus($be->getStatus()); ?></td>
                    <td>
                        <?php
                        if ($be->isBlocked()) { ?>
                            <a href="<?= $this->url('employees/employee/unblock', ['id' => $employee->getId()]); ?>"
                               onclick="return confirm('<?= $this->translate("Sei sicuro di voler sbloccare questo utente?"); ?>')"
                               class="btn-margin validation-btn btn btn-primary btn-xs">
                                <?= $this->translate("Sblocca"); ?>
                            </a>
                            <?php
                            } else if ($be->isApproved()) { ?>
                                <a href="<?= $this->url('employees/employee/block', ['id' => $employee->getId()]); ?>"
                                   onclick="return confirm('<?= $this->translate("Sei sicuro di voler bloccare questo utente?"); ?>')"
                                   class="btn-margin validation-btn btn btn-warning btn-xs">
                                    <?= $this->translate("Blocca"); ?>
                                </a>
                            <?php
                            } else { ?>
                                <a href="<?= $this->url('employees/employee/approve', ['id' => $employee->getId()]); ?>"
                                   onclick="return confirm('<?= $this->translate("Sei sicuro di voler approvare questo utente?"); ?>')"
                                   class="btn-margin validation-btn btn btn-success btn-xs">
                                    <?= $this->translate("Approva"); ?>
                                </a>
                            <?php
                            }?>
                        <a href="<?= $this->url('employees/employee/remove', ['id' => $employee->getId()]); ?>"
                           onclick="return confirm('<?= $this->translate("Sei sicuro di voler eliminare questo utente?"); ?>')"
                           class="validation-btn btn btn-danger btn-xs">
                            <?= $this->translate("Elimina"); ?>
                        </a>
                    </td>
                </tr>
                <?php
            endforeach; ?>
        </table>
    </div>
</div>