<div class="page-sidebar navbar-collapse collapse">
    <ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">

        <li class="sidebar-toggler-wrapper">
            <div class="sidebar-toggler">
            </div>
        </li>

        <?php
        $menu = '';
        $pageCount = 0;
        /** @var Zend\Navigation\Page\AbstractPage $page */
        foreach ($this->container as $page) {
            if ($this->navigation('navigation')->accept($page)) {
                $childMenu = '';
                $isChildActive = false;

                if ($page->hasPages()) {
                    $childMenu .= '<ul class="sub-menu">';
                    /** @var Zend\Navigation\Page\AbstractPage $child */
                    foreach ($page->getPages() as $child) {

                        if ($child->isActive()) {
                            $isChildActive = true;
                        }

                        if ($child->get('isVisible')) {

                            $icon = $child->get('icon');

                            $childMenu .= sprintf('<li class="%s"><a href="%s">', $child->isActive() ? 'active' : '', $child->getHref());

                            if (isset($icon)) {
                                $childMenu .= sprintf('<i class="%s"></i>', $icon);
                            }

                            $childMenu .= sprintf('%s </a></li>', $this->translate($child->getLabel()));
                        }
                    }
                    $childMenu .= '</ul>';
                }

                if ($pageCount == 0) {
                    $menu .= sprintf('<li class="%s">', $page->isActive() || $isChildActive ? 'start active open' : 'start ');
                } else {
                    $menu .= sprintf('<li class="%s">', $page->isActive() || $isChildActive ? 'active open' : '');
                }

                $isRouteJs = $page->get('isRouteJs');

                if ($page->get('openOnNewWindow')) {
                    $menu .= sprintf('<a href="%s" target="_blank">', isset($isRouteJs) ? 'javascript:;' : $page->getHref());
                } else {
                    $menu .= sprintf('<a href="%s">', isset($isRouteJs) ? 'javascript:;' : $page->getHref());
                }
                $menu .= sprintf('<i class="%s"></i>', $page->get('icon'));
                $menu .= sprintf('<span class="title">%s</span>', $this->translate($page->getLabel()));

                if ($page->hasPages()) {
                    $menu .= sprintf('<span class="arrow %s"></span>', $isChildActive ? 'open' : '');
                }

                $menu .= '</a>';

                $menu .= $childMenu;

                $menu .= '</li>';
                $pageCount++;

            }
        }

        echo $menu;
        ?>
    </ul>
</div>