<script>
    var translations = {

        //tables
        'sEmptyTable': '<?= $this->translate('Nessun elemento presente nella tabella') ?>',
        'sCarsEmptyTable': '<?= $this->translate('Nessuna auto presente nella tabella') ?>',
        'sCardsEmptyTable': '<?= $this->translate('Nessun card presente nella tabella') ?>',
        'sInvoicesEmptyTable': '<?= $this->translate('Nessuna fattura presente nella tabella') ?>',
        'sCustomersEmptyTable': '<?= $this->translate('Nessun cliente presente nella tabella') ?>',
        'sPoisEmptyTable': '<?= $this->translate('Nessun pois presente nella tabella') ?>',
        'sTripEmptyTable': '<?= $this->translate('Nessuna corsa presente nella tabella') ?>',
        'sDrivingLicenseEmptyTable': '<?= $this->translate('Nessun file caricato') ?>',
        'sInfo': '<?= $this->translate('Vista da _START_ a _END_ di _TOTAL_ elementi') ?>',
        'sInfoEmpty': '<?= $this->translate('Vista da 0 a 0 di 0 elementi') ?>',
        'sInfoFiltered': '<?= $this->translate('(filtrati da _MAX_ elementi totali)') ?>',
        'sLengthMenu': '<?= $this->translate('Visualizza _MENU_ elementi') ?>',
        'sLoadingRecords': '<?= $this->translate('Caricamento...') ?>',
        'sProcessing': '<?= $this->translate('Elaborazione in corso...') ?>',
        'sSearch': '<?= $this->translate('Cerca:') ?>',
        'sZeroRecords': '<?= $this->translate('La ricerca non ha portato alcun risultato.') ?>',
        'oPaginateFirst': '<?= $this->translate('Inizio') ?>',
        'oPaginatePrevious': '<?= $this->translate('Precedente') ?>',
        'oPaginateNext': '<?= $this->translate('Successivo') ?>',
        'oPaginateLast': '<?= $this->translate('Fine') ?>',
        'sSortAscending': '<?= $this->translate(': attiva per ordinare la colonna in ordine crescente') ?>',
        'sSortDescending': '<?= $this->translate(': attiva per ordinare la colonna in ordine decrescente') ?>',
        //employees
        'sEmptyEmployeeTable': '<?= $this->translate('Nessun dipendente presente') ?>',
        //business invoices
        'showProfileOf': '<?= $this->translate("Prosegui") ?>',
        'renderFirstPayment': '<?= $this->translate("Iscrizione") ?>',
        'renderTrip': '<?= $this->translate("Corse") ?>',
        'renderPenality': '<?= $this->translate("Sanzione") ?>',
        'renderBonusPackage': '<?= $this->translate("Pacchetto bonus") ?>',
};

    function translate(key) {
        return translations[key];
    }
</script>
