<script>
    var translations = {

        'modify': '<?= $this->translate('Modifica') ?>',
        'delete': '<?= $this->translate('Elimina') ?>',
        //tables
        'sEmptyTable': '<?= $this->translate('Nessun elemento presente nella tabella') ?>',
        'sCarsEmptyTable': '<?= $this->translate('Nessuna auto presente nella tabella') ?>',
        'sCardsEmptyTable': '<?= $this->translate('Nessun card presente nella tabella') ?>',
        'sInvoicesEmptyTable': '<?= $this->translate('Nessuna fattura presente nella tabella') ?>',
        'sCustomersEmptyTable': '<?= $this->translate('Nessun cliente presente nella tabella') ?>',
        'sPoisEmptyTable': '<?= $this->translate('Nessun pois presente nella tabella') ?>',
        'sTripEmptyTable': '<?= $this->translate('Nessuna corsa presente nella tabella') ?>',
        'sDrivingLicenseEmptyTable': '<?= $this->translate('Nessun file caricato') ?>',
        'sInfo': '<?= $this->translate('Vista da _START_ a _END_ di _TOTAL_ elementi') ?>',
        'sInfoEmpty': '<?= $this->translate('Vista da 0 a 0 di 0 elementi') ?>',
        'sInfoFiltered': '<?= $this->translate('(filtrati da _MAX_ elementi totali)') ?>',
        'sLengthMenu': '<?= $this->translate('Visualizza _MENU_ elementi') ?>',
        'sLoadingRecords': '<?= $this->translate('Caricamento...') ?>',
        'sProcessing': '<?= $this->translate('Elaborazione in corso...') ?>',
        'sSearch': '<?= $this->translate('Cerca:') ?>',
        'sZeroRecords': '<?= $this->translate('La ricerca non ha portato alcun risultato.') ?>',
        'oPaginateFirst': '<?= $this->translate('Inizio') ?>',
        'oPaginatePrevious': '<?= $this->translate('Precedente') ?>',
        'oPaginateNext': '<?= $this->translate('Successivo') ?>',
        'oPaginateLast': '<?= $this->translate('Fine') ?>',
        'sSortAscending': '<?= $this->translate(': attiva per ordinare la colonna in ordine crescente') ?>',
        'sSortDescending': '<?= $this->translate(': attiva per ordinare la colonna in ordine decrescente') ?>',
        //cars
        'confirmCarDelete': '<?= $this->translate("Confermi l\'eliminazione dell\'auto? L\'operazione non è annullabile") ?>',
        //customers-edit
        'deactivateUser': '<?= $this->translate("Disattivare utente?") ?>',
        'reactivateUser': '<?= $this->translate("Riattivare utente?") ?>',
        'removeDeactivation': '<?= $this->translate("Rimuovere disattivazione?") ?>',
        //customers
        'removeCardConfirm': '<?= $this->translate("Sei sicuro di voler rimuovere questo codice card?") ?>',
        'removeBonusConfirm': '<?= $this->translate("Sei sicuro di voler rimuovere questo bonus?") ?>',
        'ajaxError': '<?= $this->translate("Qualcosa è andato storto, riprova!") ?>',
        //edit-trip
        'confirmRemoveTries': '<?= $this->translate("La procedura di pagamento è già iniziata. Per procedere sarà necessario annullare tutti i tentativi di pagamento effettuati. Confermi di voler rimuovere tutti i tentativi di pagamento?") ?>',
        //extra-payments
        'errorId': '<?= $this->translate("Formato id cliente non corretto") ?>',
        'errorFleet': '<?= $this->translate("Selezionare una flotta") ?>',
        'errorType': '<?= $this->translate("Selezionare una tipologia") ?>',
        'errorAddDebit': '<?= $this->translate("Aggiungere almeno un addebito") ?>',
        'errorCausal': '<?= $this->translate("Inserire una causale valida") ?>',
        'errorAmount': '<?= $this->translate("Inserire un importo valido in euro") ?>',
        'confirmPayment': '<?= $this->translate("Confermi il pagamento al cliente") ?>',
        'confirmPaymentContinue': '<?= $this->translate("di un importo di") ?>',
        //failed-payments
        'tripDetailId': '<?= $this->translate("Visualizza corsa ID") ?>',
        'customersDetailId': '<?= $this->translate("Visualizza corsa ID") ?>',
        'continue': '<?= $this->translate("Prosegui") ?>',
        //invoices
        'showProfileOf': '<?= $this->translate("Prosegui") ?>',
        'renderFirstPayment': '<?= $this->translate("Iscrizione") ?>',
        'renderTrip': '<?= $this->translate("Corse") ?>',
        'renderPenality': '<?= $this->translate("Sanzione") ?>',
        'renderBonusPackage': '<?= $this->translate("Pacchetto bonus") ?>',
        //pois
        'confirmPaymentDelete': '<?= $this->translate("Confermi l\'eliminazione del poi? L\'operazione non è annullabile") ?>',
        //reservations
        'showCarPlate': '<?= $this->translate("Visualizza auto targata") ?>',
        'showProfile': '<?= $this->translate("Visualizza profilo di") ?>',
        //trip-cost
        'alertEmptyFields': '<?= $this->translate('i campi "Inizio corsa" e "Fine corsa" devono essere compilati') ?>',
        //trip
        'details': '<?= $this->translate('Dettagli') ?>',
        //foreign driver license
        'validate': '<?= $this->translate('Valida') ?>',
        'revoke': '<?= $this->translate('Revoca') ?>',
        'download': '<?= $this->translate('Scarica') ?>',
        'confirmValidate': '<?= $this->translate('Confermare la validazione?') ?>',
        'confirmRevoke': '<?= $this->translate('Confermare la revoca della patente?') ?>',
        'valid': '<?= $this->translate('Validata') ?>',
        'pending': '<?= $this->translate('Da validare') ?>',
        'revoked': '<?= $this->translate('Revocata') ?>',
        //extra-payments
        'penalty': '<?= $this->translate('Penale') ?>',
        'cause': '<?= $this->translate('Causale') ?>',
        'amount': '<?= $this->translate('Importo') ?>',
        //csv-details
        'confirmAssignBonus': '<?= $this->translate("Sei sicuro di voler assegnare questo bonus all\'utente?") ?>',
        'confirmAssignTripPayed': '<?= $this->translate('Sei sicuro di voler contrassegnare questa corsa come pagata?') ?>',
    };

    function translate(key) {
        return translations[key];
    }
</script>
