<?php
$business = $this->business
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <h3 class="page-title">
            <?= $this->translate("Primo pagamento"); ?>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">
                <?= $this->partial('partials/flash-messages.phtml', []); ?>
            </div>
            <?php
            $text = $this->translate("L'abilitiazione della sua azienda avverrà una volta completato il pagamento della quota associativa di EUR %s");
            $text = sprintf($text, $business->getReadableSubscriptionFee());
            echo $text;
            ?>
            <br>
            <form method="post">
                <input class="btn btn-success" type="submit" value="<?= $this->translate("Paga"); ?>">
            </form>
        </div>
    </div>
</div>