<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Sharengo Admin') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/palette.css'))
        ->prependStylesheet($this->basePath('css/themes/green.css'))
        ->prependStylesheet($this->basePath('css/layout.css'))
        ->prependStylesheet($this->basePath('css/plugins.css'))
        ->prependStylesheet($this->basepath('css/components.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('/css/addons.css'))
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/quick-sidebar.js'))
        ->prependFile($this->basePath('js/layout.js'))
        ->prependFile($this->basePath('js/metronic.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->basePath() .'/js/enable-enter.js')

    ; ?>
    <?php echo $this->partial('partials/translations.phtml'); ?>

</head>
<body class="page-header-fixed page-quick-sidebar-over-content">
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner">
        <div class="page-logo">
            <a href="#">
                <img src="/img/logo_white.png" alt="logo" class="logo-default" width="180"/>
            </a>
            <div class="menu-toggler sidebar-toggler hide">
            </div>
        </div>



        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
        </a>
        <div class="top-menu">
            <?php echo $this->partial('partials/menu-language.phtml', array()); ?>
        </div>
        <div class="top-menu">
            <?php echo $this->partial('partials/menu-user.phtml', array()); ?>
        </div>
    </div>
</div>

<div class="clearfix">
</div>

<div class="page-container">

    <div class="page-sidebar-wrapper">
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu'); ?>
    </div>

    <?php echo $this->content; ?>
</div>

<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner">
        <?php echo date('Y') ?> &copy; Sharengo.
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<?php echo $this->inlineScript()
    ->appendScript(
        '$(document).ready(function() {
                    Metronic.init(); // init metronic core components
                    Layout.init(); // init current layout
                    QuickSidebar.init(); // init quick sidebar
                });'
    );
?>
</body>
</html>
