<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="it">
<head>
    <meta charset="utf-8"/>
    <title>Sharengo Admin</title>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/palette.css'))
        ->prependStylesheet($this->basePath('css/custom.css'))
        ->prependStylesheet($this->basePath('css/themes/green.css'))
        ->prependStylesheet($this->basePath('css/layout.css'))
        ->prependStylesheet($this->basePath('css/plugins.css'))
        ->prependStylesheet($this->basePath('css/components.css'))
        ->prependStylesheet($this->basepath('css/login.css'))
        ->prependStylesheet($this->basePath('plugins/uniform/css/uniform.default.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('plugins/simple-line-icons/simple-line-icons.min.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/quick-sidebar.js'))
        ->prependFile($this->basePath('js/layout.js'))
        ->prependFile($this->basePath('js/metronic.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>

<body class="palette-change login">

<div class="logo">
    <a href="#">
        <img src="/img/logo_white.png" alt=""/>
    </a>
</div>

<div class="content">
    <?php echo $this->content; ?>
</div>


<div class="copyright">
    <?php echo date('Y') ?> &copy; Sharengo.
</div>

<?php echo $this->inlineScript()
    ->appendScript(
        '$(document).ready(function() {
                    Metronic.init(); // init metronic core components
                    Layout.init(); // init current layout
                    QuickSidebar.init(); // init quick sidebar
                });'
    );
?>
</body>
</html>