<?php
$this->headLink()
    ->appendStylesheet('/js/datatables/plugins/bootstrap/dataTables.bootstrap.css')
    ->appendStylesheet('/js/plugins/bootstrap-datepicker/css/datepicker3.css');
$this->headScript()
    ->appendFile('/js/datatables/media/js/jquery.dataTables.min.js')
    ->appendFile('/js/datatables/plugins/bootstrap/dataTables.bootstrap.js')
    ->appendFile('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile($this->basePath() . '/js/business-trips.js');
?>
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- BEGIN PAGE HEADER-->
        <h3 class="page-title">
            <?= $this->translate("ELENCO CORSE"); ?>
            <small><?= $this->translate("ricerca"); ?></small>
        </h3>

        <div class="page-bar">
        </div>

        <div class="row">
            <div class="col-md-12">

                <?= $this->partial('partials/flash-messages.phtml', []); ?>

                <div class="row">
                    <div class="col-md-5">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="column" id="js-column" class="form-control">
                                    <option value="select" selected>-- <?= $this->translate("Seleziona"); ?> --</option>
                                    <option value="g.name"><?= $this->translate("Gruppo"); ?></option>
                                    <option value="e.surname"><?= $this->translate("Cognome Cliente"); ?></option>

                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" name="value" value="" class="form-control" id="js-value"
                                       placeholder="<?= $this->translate("Filtra..."); ?>">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="form-inline">
                            <div class="form-group">
                                <label> <?= $this->translate("da"); ?>: </label>
                                <input class="form-control form-control-inline input-small date-picker" size="16"
                                       type="text" id="js-date-from"
                                       placeholder="<?= $this->translate("Data inizio"); ?>">
                            </div>
                            <div class="form-group">
                                <label> <?= $this->translate("a"); ?>: </label>
                                <input class="form-control form-control-inline input-small date-picker" size="16"
                                       type="text" id="js-date-to"
                                       placeholder="<?= $this->translate("Data fine"); ?>">
                            </div>
                            <div class="btn-group">
                                <button type="button" class="btn green js-search" id="js-search"><i
                                        class="fa fa-search"></i> <?= $this->translate("Cerca"); ?></button>
                                <button type="button" class="btn green dropdown-toggle" data-toggle="dropdown"><i
                                        class="fa fa-angle-down"></i></button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a id="js-clear">
                                            <i class="fa fa-remove"></i> <?= $this->translate("Pulisci Ricerca"); ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <hr>

                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?= $this->translate("Elenco Corse"); ?>
                        </div>
                    </div>

                    <div class="portlet-body">
                        <table class="table table-striped table-bordered table-hover" id="js-business-trips-table" style="overflow:hidden; white-space:nowrap">
                            <thead style="text-align-last: center">
                                <tr>
                                    <th><?= $this->translate("Id"); ?></th>
                                    <th><?= $this->translate("Cognome"); ?></th>
                                    <th><?= $this->translate("Nome"); ?></th>
                                    <th><?= $this->translate("Gruppo"); ?></th>
                                    <th><?= $this->translate("Targa auto"); ?></th>
                                    <th><?= $this->translate("Durata (min)"); ?></th>
                                    <th><?= $this->translate("Sosta (min)"); ?></th>
                                    <th><?= $this->translate("Data inizio"); ?></th>
                                    <th><?= $this->translate("Data fine"); ?></th>
                                    <th><?= $this->translate("Luogo inizio"); ?></th>
                                    <th><?= $this->translate("Luogo fine"); ?></th>
                                    
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
