<?php
$stopDiscount = $this->rate->getDiscountStop();
$tripDiscount = $this->rate->getDiscountTrip();
?>
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="page-title"><?= $this->translate("TARIFFA ATTUALE"); ?></h3>
            </div>
        </div>
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?= $this->translate("Tariffa attuale"); ?>
                </div>
            </div>
            <div class="portlet-body">
                <h3><?= $this->translate("Valido dal: ") . $this->rate->getUpdatedTs()->format('Y-m-d H:i:s'); ?></h3>
                <h3><?= $this->translate("Sconto sosta: ") . sprintf("%.2f%%", $stopDiscount * 100); ?></h3>
                <h3><?= $this->translate("Sconto corsa: ") . sprintf("%.2f%%", $tripDiscount * 100) ?></h3>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr>
                        <th></th>
                        <th><?= $this->translate('Le tue tariffe') ?></th>
                        <th><?= $this->translate('Invece di') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= $this->translate('Tariffa base della corsa') ?></td>
                        <td>€ <?= number_format(0.28 * (1 - $tripDiscount), 2, ',', '.') ?></td>
                        <td>€ 0,28</td>
                    <tr>
                    <tr>
                        <td><?= $this->translate('Tariffa di sosta') ?></td>
                        <td>€ <?= number_format(0.1 * (1 - $stopDiscount), 2, ',', '.') ?></td>
                        <td>€ 0,10</td>
                    <tr>
                    <tr>
                        <td><?= $this->translate('Tariffa per 1 ora') ?></td>
                        <td>€ <?= number_format(12 * (1 - $tripDiscount), 2, ',', '.') ?></td>
                        <td>€ 12,00</td>
                    <tr>
                    <tr>
                        <td><?= $this->translate('Tariffa per 1/2 giornata (4H)') ?></td>
                        <td>€ <?= number_format(30 * (1 - $tripDiscount), 2, ',', '.') ?></td>
                        <td>€ 30,00</td>
                    <tr>
                    <tr>
                        <td><?= $this->translate('Tariffa giornaliera') ?></td>
                        <td>€ <?= number_format(50 * (1 - $tripDiscount), 2, ',', '.') ?></td>
                        <td>€ 50,00</td>
                    <tr>
                    <tr>
                        <td><?= $this->translate('Tariffa di prenotazione') ?></td>
                        <td>€ 0,00</td>
                        <td>€ 0,00</td>
                    <tr>
                    </tbody>
                </table>

            </div>
        </div>

        <!-- END PAGE CONTENT-->
    </div>
</div>
